
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Proto import lock_pb2 as Proto_dot_lock__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Proto/lock_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.client_init = channel.unary_unary(
                '/lock_service.LockService/client_init',
                request_serializer=Proto_dot_lock__pb2.Int.SerializeToString,
                response_deserializer=Proto_dot_lock__pb2.Int.FromString,
                _registered_method=True)
        self.lock_acquire = channel.unary_unary(
                '/lock_service.LockService/lock_acquire',
                request_serializer=Proto_dot_lock__pb2.lock_args.SerializeToString,
                response_deserializer=Proto_dot_lock__pb2.Response.FromString,
                _registered_method=True)
        self.lock_release = channel.unary_unary(
                '/lock_service.LockService/lock_release',
                request_serializer=Proto_dot_lock__pb2.lock_args.SerializeToString,
                response_deserializer=Proto_dot_lock__pb2.Response.FromString,
                _registered_method=True)
        self.file_append = channel.unary_unary(
                '/lock_service.LockService/file_append',
                request_serializer=Proto_dot_lock__pb2.file_args.SerializeToString,
                response_deserializer=Proto_dot_lock__pb2.Response.FromString,
                _registered_method=True)
        self.client_close = channel.unary_unary(
                '/lock_service.LockService/client_close',
                request_serializer=Proto_dot_lock__pb2.Int.SerializeToString,
                response_deserializer=Proto_dot_lock__pb2.Int.FromString,
                _registered_method=True)
        self.heartbeat = channel.unary_unary(
                '/lock_service.LockService/heartbeat',
                request_serializer=Proto_dot_lock__pb2.Heartbeat.SerializeToString,
                response_deserializer=Proto_dot_lock__pb2.Response.FromString,
                _registered_method=True)
        self.getCurrent_lock_holder = channel.unary_unary(
                '/lock_service.LockService/getCurrent_lock_holder',
                request_serializer=Proto_dot_lock__pb2.current_lock_holder.SerializeToString,
                response_deserializer=Proto_dot_lock__pb2.Response.FromString,
                _registered_method=True)
        self.vote = channel.unary_unary(
                '/lock_service.LockService/vote',
                request_serializer=Proto_dot_lock__pb2.VoteRequest.SerializeToString,
                response_deserializer=Proto_dot_lock__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.file_append_backup = channel.unary_unary(
                '/lock_service.LockService/file_append_backup',
                request_serializer=Proto_dot_lock__pb2.FileAppendBackup.SerializeToString,
                response_deserializer=Proto_dot_lock__pb2.Response.FromString,
                _registered_method=True)
        self.log_event_primary = channel.unary_unary(
                '/lock_service.LockService/log_event_primary',
                request_serializer=Proto_dot_lock__pb2.Log.SerializeToString,
                response_deserializer=Proto_dot_lock__pb2.Response.FromString,
                _registered_method=True)
        self.sync_log = channel.unary_unary(
                '/lock_service.LockService/sync_log',
                request_serializer=Proto_dot_lock__pb2.Log.SerializeToString,
                response_deserializer=Proto_dot_lock__pb2.Response.FromString,
                _registered_method=True)
        self.sync_file = channel.unary_unary(
                '/lock_service.LockService/sync_file',
                request_serializer=Proto_dot_lock__pb2.FileAppendBackup.SerializeToString,
                response_deserializer=Proto_dot_lock__pb2.Response.FromString,
                _registered_method=True)


class LockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def client_init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def lock_acquire(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def lock_release(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def file_append(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def client_close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCurrent_lock_holder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def vote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def file_append_backup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def log_event_primary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sync_log(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sync_file(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'client_init': grpc.unary_unary_rpc_method_handler(
                    servicer.client_init,
                    request_deserializer=Proto_dot_lock__pb2.Int.FromString,
                    response_serializer=Proto_dot_lock__pb2.Int.SerializeToString,
            ),
            'lock_acquire': grpc.unary_unary_rpc_method_handler(
                    servicer.lock_acquire,
                    request_deserializer=Proto_dot_lock__pb2.lock_args.FromString,
                    response_serializer=Proto_dot_lock__pb2.Response.SerializeToString,
            ),
            'lock_release': grpc.unary_unary_rpc_method_handler(
                    servicer.lock_release,
                    request_deserializer=Proto_dot_lock__pb2.lock_args.FromString,
                    response_serializer=Proto_dot_lock__pb2.Response.SerializeToString,
            ),
            'file_append': grpc.unary_unary_rpc_method_handler(
                    servicer.file_append,
                    request_deserializer=Proto_dot_lock__pb2.file_args.FromString,
                    response_serializer=Proto_dot_lock__pb2.Response.SerializeToString,
            ),
            'client_close': grpc.unary_unary_rpc_method_handler(
                    servicer.client_close,
                    request_deserializer=Proto_dot_lock__pb2.Int.FromString,
                    response_serializer=Proto_dot_lock__pb2.Int.SerializeToString,
            ),
            'heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.heartbeat,
                    request_deserializer=Proto_dot_lock__pb2.Heartbeat.FromString,
                    response_serializer=Proto_dot_lock__pb2.Response.SerializeToString,
            ),
            'getCurrent_lock_holder': grpc.unary_unary_rpc_method_handler(
                    servicer.getCurrent_lock_holder,
                    request_deserializer=Proto_dot_lock__pb2.current_lock_holder.FromString,
                    response_serializer=Proto_dot_lock__pb2.Response.SerializeToString,
            ),
            'vote': grpc.unary_unary_rpc_method_handler(
                    servicer.vote,
                    request_deserializer=Proto_dot_lock__pb2.VoteRequest.FromString,
                    response_serializer=Proto_dot_lock__pb2.VoteResponse.SerializeToString,
            ),
            'file_append_backup': grpc.unary_unary_rpc_method_handler(
                    servicer.file_append_backup,
                    request_deserializer=Proto_dot_lock__pb2.FileAppendBackup.FromString,
                    response_serializer=Proto_dot_lock__pb2.Response.SerializeToString,
            ),
            'log_event_primary': grpc.unary_unary_rpc_method_handler(
                    servicer.log_event_primary,
                    request_deserializer=Proto_dot_lock__pb2.Log.FromString,
                    response_serializer=Proto_dot_lock__pb2.Response.SerializeToString,
            ),
            'sync_log': grpc.unary_unary_rpc_method_handler(
                    servicer.sync_log,
                    request_deserializer=Proto_dot_lock__pb2.Log.FromString,
                    response_serializer=Proto_dot_lock__pb2.Response.SerializeToString,
            ),
            'sync_file': grpc.unary_unary_rpc_method_handler(
                    servicer.sync_file,
                    request_deserializer=Proto_dot_lock__pb2.FileAppendBackup.FromString,
                    response_serializer=Proto_dot_lock__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lock_service.LockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lock_service.LockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def client_init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lock_service.LockService/client_init',
            Proto_dot_lock__pb2.Int.SerializeToString,
            Proto_dot_lock__pb2.Int.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def lock_acquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lock_service.LockService/lock_acquire',
            Proto_dot_lock__pb2.lock_args.SerializeToString,
            Proto_dot_lock__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def lock_release(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lock_service.LockService/lock_release',
            Proto_dot_lock__pb2.lock_args.SerializeToString,
            Proto_dot_lock__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def file_append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lock_service.LockService/file_append',
            Proto_dot_lock__pb2.file_args.SerializeToString,
            Proto_dot_lock__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def client_close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lock_service.LockService/client_close',
            Proto_dot_lock__pb2.Int.SerializeToString,
            Proto_dot_lock__pb2.Int.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lock_service.LockService/heartbeat',
            Proto_dot_lock__pb2.Heartbeat.SerializeToString,
            Proto_dot_lock__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCurrent_lock_holder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lock_service.LockService/getCurrent_lock_holder',
            Proto_dot_lock__pb2.current_lock_holder.SerializeToString,
            Proto_dot_lock__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lock_service.LockService/vote',
            Proto_dot_lock__pb2.VoteRequest.SerializeToString,
            Proto_dot_lock__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def file_append_backup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lock_service.LockService/file_append_backup',
            Proto_dot_lock__pb2.FileAppendBackup.SerializeToString,
            Proto_dot_lock__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def log_event_primary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lock_service.LockService/log_event_primary',
            Proto_dot_lock__pb2.Log.SerializeToString,
            Proto_dot_lock__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sync_log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lock_service.LockService/sync_log',
            Proto_dot_lock__pb2.Log.SerializeToString,
            Proto_dot_lock__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sync_file(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lock_service.LockService/sync_file',
            Proto_dot_lock__pb2.FileAppendBackup.SerializeToString,
            Proto_dot_lock__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
